baseurl = "https://zhuzhenghao.github.io/braindump/"
metaDataFormat = "yaml"
title = "ATS 前端技术"
theme = "blist"

DefaultContentLanguage = "zh-cn"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.zh-cn]
    contentDir = "content/zh-cn" #Chinese
    weight = 1
    languageName = "中文"
    [languages.zh-cn.params]
      introTitle = "Hey! I'm a happy dog."
      introSubtitle = "This website, 'Frontend Technology', serves as a platform to share insightful articles in the field of frontend development. Our aim is to foster knowledge sharing and collaboration, and to keep our team updated with the latest trends and best practices in frontend technology. Whether you're a seasoned developer or just starting out, we hope you'll find these resources valuable and inspiring."
      introPhoto = "intro.png"
      logo = "happy-dog.png"
    [[languages.zh-cn.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.zh-cn.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.zh-cn.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.zh-cn.menu.main]]
        name = "Top Post"
        url = "/zh-cn/blog/emoji-support/"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - Happy Dog · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/"
  [[params.homepage.social.icons]]
    website = "xing"
    url = "https://www.xing.com/profile/"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/"
  [[params.homepage.social.icons]]
    website = "buymeacoffee"
    url = "https://www.buymeacoffee.com/"
  [[params.homepage.social.icons]]
    website = "medium"
    url = "https://medium.com/"
  [[params.homepage.social.icons]]
    website = "reddit"
    url = "https://reddit.com/"
  [[params.homepage.social.icons]]
    website = "dribbble"
    url = "https://dribbble.com/"
  [[params.homepage.social.icons]]
    website = "stackoverflow"
    url = "https://stackoverflow.com/"
  [[params.homepage.social.icons]]
    website = "xda"
    url = "https://forum.xda-developers.com/"
  [[params.homepage.social.icons]]
    website = "tiktok"
    url = "https://tiktok.com"
  [[params.homepage.social.icons]]
    website = "googlescholar"
    url = "https://scholar.google.com/"
  [[params.homepage.social.icons]]
    website = "mastodon"
    url = "https://joinmastodon.org"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://youtube.com"
  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://instagram.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://facebook.com"
  [[params.homepage.social.icons]]
    website = "behance"
    url = "https://behance.net"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
